module.exports = {
    signup: require("./user/signup"),
    signin: require("./user/signin"),
    signout: require("./user/signout"),
    withdrawal: require("./user/withdrawal"),
    emailCode: require("./user/emailCode"),
    emailVerification: require("./user/emailVerification"),
    googleSignin: require("./google/signin"),
    googleSignout: require("./google/signout"),
    googleWithdrawal: require("./google/withdrawal"),
    registration: require("./place/registration"),
    category: require("./place/category"),
    select: require("./place/select"),
    createFavorites: require("./place/createFavorites"),
    cancelFavorites: require("./place/cancelFavorites"),
    createReview: require("./place/createReview"),
    updateUserInfo: require("./mypage/updateUserInfo"),
    getUserInfo: require("./mypage/getUserInfo"),
    getFavorites: require("./mypage/getFavorites"),
    getReview: require("./mypage/getReview"),
  };  